package swingcubemove;

import java.awt.Point;
import java.util.Random;

public class JBoxFrame extends javax.swing.JFrame {

   // my fields
   private static final int STEP = 5;
   private int kx, ky;
   private MoveThread thread;

   /**
    * Creates new form JBoxFrame
    */
   public JBoxFrame() {
      initComponents();
      kx = ky = 1;
      Random rnd = new Random();
      jPanel2.setLayout(null);
      jBox.setLocation(rnd.nextInt(jPanel2.getWidth() - jBox.getWidth()),
              rnd.nextInt(jPanel2.getHeight() - jBox.getHeight()));
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jStartBtn = new javax.swing.JButton();
      jStopBtn = new javax.swing.JButton();
      jExitBtn = new javax.swing.JButton();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jBox = new javax.swing.JPanel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

      jStartBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
      jStartBtn.setText("Start");
      jStartBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jStartMove(evt);
         }
      });

      jStopBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
      jStopBtn.setText("Stop");
      jStopBtn.setEnabled(false);
      jStopBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jStopMove(evt);
         }
      });

      jExitBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
      jExitBtn.setText("Exit");
      jExitBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jExit(evt);
         }
      });

      jButton1.setText("Up");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jUpSpeed(evt);
         }
      });

      jButton2.setText("Down");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jDownSpeed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(jStartBtn)
            .addGap(18, 18, 18)
            .addComponent(jStopBtn)
            .addGap(68, 68, 68)
            .addComponent(jButton1)
            .addGap(18, 18, 18)
            .addComponent(jButton2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jStartBtn)
               .addComponent(jStopBtn)
               .addComponent(jExitBtn)
               .addComponent(jButton1)
               .addComponent(jButton2))
            .addGap(29, 29, 29))
      );

      jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

      jBox.setBackground(new java.awt.Color(255, 204, 0));
      jBox.setPreferredSize(new java.awt.Dimension(30, 30));

      javax.swing.GroupLayout jBoxLayout = new javax.swing.GroupLayout(jBox);
      jBox.setLayout(jBoxLayout);
      jBoxLayout.setHorizontalGroup(
         jBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 30, Short.MAX_VALUE)
      );
      jBoxLayout.setVerticalGroup(
         jBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 30, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(131, 131, 131)
            .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(530, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(65, 65, 65)
            .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(261, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
   // start move box
   private void jStartMove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartMove
      thread = new MoveThread(this, 50);
      thread.start();
      switchButtons();
   }//GEN-LAST:event_jStartMove

   // stop move box
   private void jStopMove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStopMove
      thread.stop();
      switchButtons();
   }//GEN-LAST:event_jStopMove

   // close window
   private void jExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExit
      this.dispose();
   }//GEN-LAST:event_jExit

   private void jDownSpeed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDownSpeed
     thread.setDelay(thread.getDelay() + 5);
   }//GEN-LAST:event_jDownSpeed

   private void jUpSpeed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpSpeed
      thread.setDelay(thread.getDelay() - 5);
   }//GEN-LAST:event_jUpSpeed

   // switch start-stop buttons
   private void switchButtons(){
      jStartBtn.setEnabled(!jStartBtn.isEnabled());
      jStopBtn.setEnabled(!jStopBtn.isEnabled());
   }
   
   // move box
   public void moveBox() {
      Point p = jBox.getLocation();
      
      if ((p.x >= jPanel2.getWidth() - jBox.getWidth()) || (p.x <= 0)) {
         kx = -kx;
      }
      
      if ((p.y >= jPanel2.getHeight()- jBox.getHeight()) || (p.y <= 0)) {
         ky = -ky;
      }
      
      p.move(p.x + kx * STEP, p.y + ky * STEP);
      jBox.setLocation(p);
   }

   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         @Override
         public void run() {
            new JBoxFrame().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel jBox;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jExitBtn;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JButton jStartBtn;
   private javax.swing.JButton jStopBtn;
   // End of variables declaration//GEN-END:variables
}
